..................................................FFFFFFFFFF............ [  8%]
........................F......s.....................FFFFFF+++++++++++++++++++++++++++++++++++ Timeout ++++++++++++++++++++++++++++++++++++
~~~~~~~~~~~ Stack of communication_queue_processor (127890897233600) ~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/common/communication_manager.py", line 352, in run_queue_processor
    loop.run_until_complete(self._process_channel_queues())
  File "/usr/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1949, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.12/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
~~~~~~~~~~~~~~~~~ Stack of Thread-51 (_run) (127890880448192) ~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/interval_runner.py", line 19, in _run
    self.target()
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/client.py", line 155, in process_messages
    self.process_message()
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/client.py", line 103, in process_message
    raw_message = self.message_queue.get(timeout=1)
  File "/usr/lib/python3.12/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~~~~~~~ Stack of Thread-49 (_run) (127890888840896) ~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/interval_runner.py", line 20, in _run
    self.event.wait(self.interval_seconds)
  File "/usr/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~ Stack of communication_queue_processor (127891400533696) ~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/common/communication_manager.py", line 352, in run_queue_processor
    loop.run_until_complete(self._process_channel_queues())
  File "/usr/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1949, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.12/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
~~~~~~~~~~~~~~~~~ Stack of Thread-48 (_run) (127890905626304) ~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/interval_runner.py", line 19, in _run
    self.target()
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/client.py", line 155, in process_messages
    self.process_message()
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/client.py", line 103, in process_message
    raw_message = self.message_queue.get(timeout=1)
  File "/usr/lib/python3.12/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~~~~~~~ Stack of Thread-46 (_run) (127891392140992) ~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/interval_runner.py", line 20, in _run
    self.event.wait(self.interval_seconds)
  File "/usr/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~ Stack of communication_queue_processor (127891425711808) ~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/common/communication_manager.py", line 352, in run_queue_processor
    loop.run_until_complete(self._process_channel_queues())
  File "/usr/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1949, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.12/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
~~~~~~~~~~~~~~~~~ Stack of Thread-45 (_run) (127891408926400) ~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/interval_runner.py", line 19, in _run
    self.target()
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/client.py", line 155, in process_messages
    self.process_message()
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/client.py", line 103, in process_message
    raw_message = self.message_queue.get(timeout=1)
  File "/usr/lib/python3.12/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~~~~~~~ Stack of Thread-43 (_run) (127891417319104) ~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/interval_runner.py", line 20, in _run
    self.event.wait(self.interval_seconds)
  File "/usr/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~ Stack of communication_queue_processor (127891929011904) ~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/common/communication_manager.py", line 352, in run_queue_processor
    loop.run_until_complete(self._process_channel_queues())
  File "/usr/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1949, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.12/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
~~~~~~~~~~~~~~~~~ Stack of Thread-42 (_run) (127891434104512) ~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/interval_runner.py", line 19, in _run
    self.target()
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/client.py", line 155, in process_messages
    self.process_message()
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/client.py", line 103, in process_message
    raw_message = self.message_queue.get(timeout=1)
  File "/usr/lib/python3.12/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~~~~~~~ Stack of Thread-40 (_run) (127891442497216) ~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/interval_runner.py", line 20, in _run
    self.event.wait(self.interval_seconds)
  File "/usr/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~ Stack of communication_queue_processor (127891954190016) ~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/common/communication_manager.py", line 352, in run_queue_processor
    loop.run_until_complete(self._process_channel_queues())
  File "/usr/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1949, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.12/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
~~~~~~~~~~~~~~~~~ Stack of Thread-39 (_run) (127891937404608) ~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/interval_runner.py", line 19, in _run
    self.target()
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/client.py", line 155, in process_messages
    self.process_message()
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/client.py", line 103, in process_message
    raw_message = self.message_queue.get(timeout=1)
  File "/usr/lib/python3.12/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~~~~~~~ Stack of Thread-37 (_run) (127891945797312) ~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/interval_runner.py", line 20, in _run
    self.event.wait(self.interval_seconds)
  File "/usr/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~ Stack of communication_queue_processor (127892474275520) ~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/common/communication_manager.py", line 352, in run_queue_processor
    loop.run_until_complete(self._process_channel_queues())
  File "/usr/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1949, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.12/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
~~~~~~~~~~~~~~~~~ Stack of Thread-36 (_run) (127891962582720) ~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/interval_runner.py", line 19, in _run
    self.target()
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/client.py", line 155, in process_messages
    self.process_message()
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/client.py", line 103, in process_message
    raw_message = self.message_queue.get(timeout=1)
  File "/usr/lib/python3.12/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~~~~~~~ Stack of Thread-34 (_run) (127891970975424) ~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/interval_runner.py", line 20, in _run
    self.event.wait(self.interval_seconds)
  File "/usr/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~ Stack of communication_queue_processor (127892482668224) ~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/common/communication_manager.py", line 352, in run_queue_processor
    loop.run_until_complete(self._process_channel_queues())
  File "/usr/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
    handle = None  # Needed to break cycles when an exception occurs.
  File "/usr/lib/python3.12/selectors.py", line 481, in select
    return ready
~~~~~~~~~~~~~~~~~ Stack of Thread-33 (_run) (127891979368128) ~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/interval_runner.py", line 19, in _run
    self.target()
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/client.py", line 155, in process_messages
    self.process_message()
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/client.py", line 103, in process_message
    raw_message = self.message_queue.get(timeout=1)
  File "/usr/lib/python3.12/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~~~~~~~ Stack of Thread-31 (_run) (127892465882816) ~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/interval_runner.py", line 20, in _run
    self.event.wait(self.interval_seconds)
  File "/usr/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~ Stack of communication_queue_processor (127892507846336) ~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/common/communication_manager.py", line 352, in run_queue_processor
    loop.run_until_complete(self._process_channel_queues())
  File "/usr/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1949, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.12/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
~~~~~~~~~~~~~~~~~ Stack of Thread-30 (_run) (127892491060928) ~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/interval_runner.py", line 19, in _run
    self.target()
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/client.py", line 155, in process_messages
    self.process_message()
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/client.py", line 103, in process_message
    raw_message = self.message_queue.get(timeout=1)
  File "/usr/lib/python3.12/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~~~~~~~ Stack of Thread-28 (_run) (127892499453632) ~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/interval_runner.py", line 20, in _run
    self.event.wait(self.interval_seconds)
  File "/usr/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~ Stack of communication_queue_processor (127893011146432) ~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/common/communication_manager.py", line 352, in run_queue_processor
    loop.run_until_complete(self._process_channel_queues())
  File "/usr/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1949, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.12/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
~~~~~~~~~~~~~~~~~ Stack of Thread-27 (_run) (127892516239040) ~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/interval_runner.py", line 19, in _run
    self.target()
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/client.py", line 155, in process_messages
    self.process_message()
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/client.py", line 103, in process_message
    raw_message = self.message_queue.get(timeout=1)
  File "/usr/lib/python3.12/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~~~~~~~ Stack of Thread-25 (_run) (127893002753728) ~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/interval_runner.py", line 20, in _run
    self.event.wait(self.interval_seconds)
  File "/usr/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~ Stack of communication_queue_processor (127893539624640) ~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/common/communication_manager.py", line 352, in run_queue_processor
    loop.run_until_complete(self._process_channel_queues())
  File "/usr/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1949, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.12/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
~~~~~~~~~~~~~~~~~ Stack of Thread-24 (_run) (127893019539136) ~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/interval_runner.py", line 19, in _run
    self.target()
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/client.py", line 155, in process_messages
    self.process_message()
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/client.py", line 103, in process_message
    raw_message = self.message_queue.get(timeout=1)
  File "/usr/lib/python3.12/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~~~~~~~ Stack of Thread-22 (_run) (127893027931840) ~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/interval_runner.py", line 20, in _run
    self.event.wait(self.interval_seconds)
  File "/usr/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~ Stack of communication_queue_processor (127893036324544) ~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/common/communication_manager.py", line 352, in run_queue_processor
    loop.run_until_complete(self._process_channel_queues())
  File "/usr/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
    handle = None  # Needed to break cycles when an exception occurs.
  File "/usr/lib/python3.12/selectors.py", line 481, in select
    return ready
~~~~~~~~~~~~~~~~~ Stack of Thread-21 (_run) (127893044717248) ~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/interval_runner.py", line 19, in _run
    self.target()
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/client.py", line 155, in process_messages
    self.process_message()
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/client.py", line 103, in process_message
    raw_message = self.message_queue.get(timeout=1)
  File "/usr/lib/python3.12/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~~~~~~~ Stack of Thread-19 (_run) (127893053109952) ~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/interval_runner.py", line 20, in _run
    self.event.wait(self.interval_seconds)
  File "/usr/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~ Stack of communication_queue_processor (127893564802752) ~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/common/communication_manager.py", line 352, in run_queue_processor
    loop.run_until_complete(self._process_channel_queues())
  File "/usr/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1949, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.12/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
~~~~~~~~~~~~~~~~~ Stack of Thread-18 (_run) (127893548017344) ~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/interval_runner.py", line 19, in _run
    self.target()
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/client.py", line 155, in process_messages
    self.process_message()
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/client.py", line 103, in process_message
    raw_message = self.message_queue.get(timeout=1)
  File "/usr/lib/python3.12/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~~~~~~~ Stack of Thread-16 (_run) (127893556410048) ~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/interval_runner.py", line 20, in _run
    self.event.wait(self.interval_seconds)
  File "/usr/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~ Stack of communication_queue_processor (127893589980864) ~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/common/communication_manager.py", line 352, in run_queue_processor
    loop.run_until_complete(self._process_channel_queues())
  File "/usr/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1949, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.12/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
~~~~~~~~~~~~~~~~~ Stack of Thread-15 (_run) (127893573195456) ~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/interval_runner.py", line 19, in _run
    self.target()
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/client.py", line 155, in process_messages
    self.process_message()
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/client.py", line 103, in process_message
    raw_message = self.message_queue.get(timeout=1)
  File "/usr/lib/python3.12/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~~~~~~~ Stack of Thread-13 (_run) (127893581588160) ~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/interval_runner.py", line 20, in _run
    self.event.wait(self.interval_seconds)
  File "/usr/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~ Stack of communication_queue_processor (127894093280960) ~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/common/communication_manager.py", line 352, in run_queue_processor
    loop.run_until_complete(self._process_channel_queues())
  File "/usr/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
    handle = None  # Needed to break cycles when an exception occurs.
  File "/usr/lib/python3.12/selectors.py", line 481, in select
    return ready
~~~~~~~~~~~~~~~~~ Stack of Thread-12 (_run) (127894076495552) ~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/interval_runner.py", line 19, in _run
    self.target()
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/client.py", line 155, in process_messages
    self.process_message()
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/client.py", line 103, in process_message
    raw_message = self.message_queue.get(timeout=1)
  File "/usr/lib/python3.12/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~~~~~~~ Stack of Thread-10 (_run) (127894084888256) ~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/interval_runner.py", line 20, in _run
    self.event.wait(self.interval_seconds)
  File "/usr/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~ Stack of communication_queue_processor (127894118459072) ~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/common/communication_manager.py", line 352, in run_queue_processor
    loop.run_until_complete(self._process_channel_queues())
  File "/usr/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1949, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.12/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
~~~~~~~~~~~~~~~~~~ Stack of Thread-9 (_run) (127894101673664) ~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/interval_runner.py", line 19, in _run
    self.target()
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/client.py", line 155, in process_messages
    self.process_message()
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/client.py", line 103, in process_message
    raw_message = self.message_queue.get(timeout=1)
  File "/usr/lib/python3.12/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~~~~~~~~ Stack of Thread-7 (_run) (127894110066368) ~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/interval_runner.py", line 20, in _run
    self.event.wait(self.interval_seconds)
  File "/usr/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~ Stack of communication_queue_processor (127894512727744) ~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/common/communication_manager.py", line 352, in run_queue_processor
    loop.run_until_complete(self._process_channel_queues())
  File "/usr/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1949, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.12/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
~~~~~~~~~~~~~~~~~~ Stack of Thread-6 (_run) (127894126851776) ~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/interval_runner.py", line 19, in _run
    self.target()
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/client.py", line 155, in process_messages
    self.process_message()
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/client.py", line 103, in process_message
    raw_message = self.message_queue.get(timeout=1)
  File "/usr/lib/python3.12/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~~~~~~~~ Stack of Thread-4 (_run) (127894476011200) ~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/interval_runner.py", line 20, in _run
    self.event.wait(self.interval_seconds)
  File "/usr/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~~~~~~~~ Stack of Thread-3 (_run) (127894487549632) ~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/interval_runner.py", line 19, in _run
    self.target()
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/client.py", line 155, in process_messages
    self.process_message()
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/client.py", line 103, in process_message
    raw_message = self.message_queue.get(timeout=1)
  File "/usr/lib/python3.12/queue.py", line 180, in get
    self.not_empty.wait(remaining)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~~~~~~~~ Stack of Thread-1 (_run) (127894495942336) ~~~~~~~~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/slack_sdk/socket_mode/interval_runner.py", line 20, in _run
    self.event.wait(self.interval_seconds)
  File "/usr/lib/python3.12/threading.py", line 655, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.12/threading.py", line 359, in wait
    gotit = waiter.acquire(True, timeout)
~~~~~~~~~~~ Stack of communication_queue_processor (127894504335040) ~~~~~~~~~~~
  File "/usr/lib/python3.12/threading.py", line 1030, in _bootstrap
    self._bootstrap_inner()
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mikekao/personal/generative-agent/common/communication_manager.py", line 352, in run_queue_processor
    loop.run_until_complete(self._process_channel_queues())
  File "/usr/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1949, in _run_once
    event_list = self._selector.select(timeout)
  File "/usr/lib/python3.12/selectors.py", line 468, in select
    fd_event_list = self._selector.poll(timeout, max_ev)
+++++++++++++++++++++++++++++++++++ Timeout ++++++++++++++++++++++++++++++++++++
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/_pytest/main.py", line 289, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/_pytest/main.py", line 343, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/pluggy/_hooks.py", line 512, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/pluggy/_manager.py", line 120, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/pluggy/_callers.py", line 167, in _multicall
INTERNALERROR>     raise exception
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/pluggy/_callers.py", line 139, in _multicall
INTERNALERROR>     teardown.throw(exception)
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/_pytest/logging.py", line 801, in pytest_runtestloop
INTERNALERROR>     return (yield)  # Run all the tests.
INTERNALERROR>             ^^^^^
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/pluggy/_callers.py", line 139, in _multicall
INTERNALERROR>     teardown.throw(exception)
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/_pytest/terminal.py", line 688, in pytest_runtestloop
INTERNALERROR>     result = yield
INTERNALERROR>              ^^^^^
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/pluggy/_callers.py", line 139, in _multicall
INTERNALERROR>     teardown.throw(exception)
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/pytest_cov/plugin.py", line 345, in pytest_runtestloop
INTERNALERROR>     result = yield
INTERNALERROR>              ^^^^^
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/pluggy/_callers.py", line 121, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/_pytest/main.py", line 367, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/pluggy/_hooks.py", line 512, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/pluggy/_manager.py", line 120, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/pluggy/_callers.py", line 167, in _multicall
INTERNALERROR>     raise exception
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/pluggy/_callers.py", line 139, in _multicall
INTERNALERROR>     teardown.throw(exception)
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/_pytest/warnings.py", line 90, in pytest_runtest_protocol
INTERNALERROR>     return (yield)
INTERNALERROR>             ^^^^^
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/pluggy/_callers.py", line 139, in _multicall
INTERNALERROR>     teardown.throw(exception)
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/_pytest/assertion/__init__.py", line 192, in pytest_runtest_protocol
INTERNALERROR>     return (yield)
INTERNALERROR>             ^^^^^
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/pluggy/_callers.py", line 139, in _multicall
INTERNALERROR>     teardown.throw(exception)
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/pluggy/_callers.py", line 53, in run_old_style_hookwrapper
INTERNALERROR>     return result.get_result()
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/pluggy/_result.py", line 103, in get_result
INTERNALERROR>     raise exc.with_traceback(tb)
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/pluggy/_callers.py", line 38, in run_old_style_hookwrapper
INTERNALERROR>     res = yield
INTERNALERROR>           ^^^^^
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/pluggy/_callers.py", line 139, in _multicall
INTERNALERROR>     teardown.throw(exception)
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/_pytest/unittest.py", line 475, in pytest_runtest_protocol
INTERNALERROR>     return (yield)
INTERNALERROR>             ^^^^^
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/pluggy/_callers.py", line 139, in _multicall
INTERNALERROR>     teardown.throw(exception)
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/_pytest/faulthandler.py", line 88, in pytest_runtest_protocol
INTERNALERROR>     return (yield)
INTERNALERROR>             ^^^^^
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/pluggy/_callers.py", line 121, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/_pytest/runner.py", line 117, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/_pytest/runner.py", line 136, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/_pytest/runner.py", line 248, in call_and_report
INTERNALERROR>     report: TestReport = ihook.pytest_runtest_makereport(item=item, call=call)
INTERNALERROR>                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/pluggy/_hooks.py", line 512, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/pluggy/_manager.py", line 120, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/pluggy/_callers.py", line 167, in _multicall
INTERNALERROR>     raise exception
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/pluggy/_callers.py", line 139, in _multicall
INTERNALERROR>     teardown.throw(exception)
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/_pytest/tmpdir.py", line 308, in pytest_runtest_makereport
INTERNALERROR>     rep = yield
INTERNALERROR>           ^^^^^
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/pluggy/_callers.py", line 139, in _multicall
INTERNALERROR>     teardown.throw(exception)
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/pluggy/_callers.py", line 53, in run_old_style_hookwrapper
INTERNALERROR>     return result.get_result()
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/pluggy/_result.py", line 103, in get_result
INTERNALERROR>     raise exc.with_traceback(tb)
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/pluggy/_callers.py", line 38, in run_old_style_hookwrapper
INTERNALERROR>     res = yield
INTERNALERROR>           ^^^^^
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/pluggy/_callers.py", line 139, in _multicall
INTERNALERROR>     teardown.throw(exception)
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/_pytest/skipping.py", line 275, in pytest_runtest_makereport
INTERNALERROR>     rep = yield
INTERNALERROR>           ^^^^^
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/pluggy/_callers.py", line 121, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>           ^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/_pytest/runner.py", line 368, in pytest_runtest_makereport
INTERNALERROR>     return TestReport.from_item_and_call(item, call)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/_pytest/reports.py", line 377, in from_item_and_call
INTERNALERROR>     longrepr = item.repr_failure(excinfo)
INTERNALERROR>                ^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/_pytest/python.py", line 1713, in repr_failure
INTERNALERROR>     return self._repr_failure_py(excinfo, style=style)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/_pytest/nodes.py", line 456, in _repr_failure_py
INTERNALERROR>     return excinfo.getrepr(
INTERNALERROR>            ^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/_pytest/_code/code.py", line 766, in getrepr
INTERNALERROR>     return fmt.repr_excinfo(self)
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/_pytest/_code/code.py", line 1202, in repr_excinfo
INTERNALERROR>     reprtraceback = self.repr_traceback(excinfo_)
INTERNALERROR>                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/_pytest/_code/code.py", line 1135, in repr_traceback
INTERNALERROR>     self.repr_traceback_entry(entry, excinfo if last == entry else None)
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/_pytest/_code/code.py", line 1102, in repr_traceback_entry
INTERNALERROR>     lines.extend(self.get_exconly(excinfo, indent=4))
INTERNALERROR>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/_pytest/_code/code.py", line 1019, in get_exconly
INTERNALERROR>     exlines = excinfo.exconly(tryshort=True).split("\n")
INTERNALERROR>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/_pytest/_code/code.py", line 669, in exconly
INTERNALERROR>     lines = format_exception_only(self.type, self.value)
INTERNALERROR>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/usr/lib/python3.12/traceback.py", line 156, in format_exception_only
INTERNALERROR>     te = TracebackException(type(value), value, None, compact=True)
INTERNALERROR>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/usr/lib/python3.12/traceback.py", line 811, in __init__
INTERNALERROR>     context = TracebackException(
INTERNALERROR>               ^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/usr/lib/python3.12/traceback.py", line 733, in __init__
INTERNALERROR>     self.stack = StackSummary._extract_from_extended_frame_gen(
INTERNALERROR>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/usr/lib/python3.12/traceback.py", line 418, in _extract_from_extended_frame_gen
INTERNALERROR>     for f, (lineno, end_lineno, colno, end_colno) in frame_gen:
INTERNALERROR>   File "/usr/lib/python3.12/traceback.py", line 355, in _walk_tb_with_full_positions
INTERNALERROR>     positions = _get_code_position(tb.tb_frame.f_code, tb.tb_lasti)
INTERNALERROR>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/usr/lib/python3.12/traceback.py", line 369, in _get_code_position
INTERNALERROR>     return next(itertools.islice(positions_gen, instruction_index // 2, None))
INTERNALERROR>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/pytest_timeout.py", line 317, in handler
INTERNALERROR>     timeout_sigalrm(item, settings)
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/pytest_timeout.py", line 502, in timeout_sigalrm
INTERNALERROR>     pytest.fail(PYTEST_FAILURE_MESSAGE % settings.timeout)
INTERNALERROR>   File "/home/mikekao/personal/generative-agent/venv/lib/python3.12/site-packages/_pytest/outcomes.py", line 177, in fail
INTERNALERROR>     raise Failed(msg=reason, pytrace=pytrace)
INTERNALERROR> Failed: Timeout (>10.0s) from pytest-timeout.

17 failed, 113 passed, 1 skipped in 33.54s
